"""SLURM script generation for multi-node OrthoFinder execution.

The multi-node mode splits OrthoFinder into three chained jobs:

1. **Prepare** — runs ``orthofinder -op`` on a single node to format inputs
   and emit the list of DIAMOND/BLAST search commands.
2. **Search array** — a SLURM array job that distributes those search
   commands across multiple nodes.
3. **Resume** — runs ``orthofinder -b <workdir>`` on a single node once
   all search commands are done, performing clustering, MSA, and tree
   inference.
"""

from __future__ import annotations

from datetime import datetime

from convgeno.slurm.config import PipelineConfig


def _build_sbatch_header(config: PipelineConfig, overrides: dict) -> str:
    """Build SBATCH header lines from ``config.slurm`` with field overrides.

    Returns the lines joined into a single ``\\n``-separated string.
    """
    lines: dict[str, str] = {
        "--partition": config.slurm.partition,
        "--nodes": str(config.slurm.nodes),
        "--ntasks": str(config.slurm.ntasks),
        "--cpus-per-task": str(config.slurm.cpus_per_task),
        "--time": config.slurm.time_limit,
        "--mem-per-cpu": config.slurm.mem_per_cpu,
        "--output": config.slurm.output_pattern,
        "--error": config.slurm.error_pattern,
    }
    if config.slurm.account is not None:
        lines["--account"] = config.slurm.account
    if config.slurm.mail_user is not None:
        lines["--mail-user"] = config.slurm.mail_user
        lines["--mail-type"] = config.slurm.mail_type

    lines.update(overrides)

    formatted = [f"#SBATCH {flag}={value}" for flag, value in lines.items()]
    for arg in config.slurm.extra_sbatch_args:
        formatted.append(f"#SBATCH {arg}")
    return "\n".join(formatted)


def _validate_has_orthofinder(config: PipelineConfig) -> None:
    if config.orthofinder is None:
        raise ValueError(
            "OrthoFinder settings not found in pipeline config. "
            "Add an 'orthofinder' section to pipeline_config.yaml."
        )


def generate_prepare_script(config: PipelineConfig) -> str:
    """Generate SLURM script for OrthoFinder's prepare phase (``-op``).

    Runs on a single node. Captures the DIAMOND/BLAST commands to a file
    for the array job.
    """
    _validate_has_orthofinder(config)
    assert config.orthofinder is not None  # for type checker

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    header = _build_sbatch_header(
        config,
        overrides={
            "--job-name": "convgeno_of_prepare",
            "--nodes": "1",
            "--ntasks": "1",
            "--cpus-per-task": "4",
            "--time": "02:00:00",
        },
    )

    script = f"""\
#!/bin/bash
# ============================================================
# OrthoFinder prepare phase (-op) — multi-node mode
# Generated by convgeno on {timestamp}
# ============================================================

{header}

set -euo pipefail

echo "============================================================"
echo "convgeno: OrthoFinder prepare phase started"
echo "Job ID:    $SLURM_JOB_ID"
echo "Node:      $HOSTNAME"
echo "Start:     $(date)"
echo "============================================================"

START_SECONDS=$SECONDS

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate {config.conda_env}

INPUT_DIR="{config.orthofinder.input_dir}"
OUTPUT_DIR="{config.orthofinder.output_dir}"
COMMANDS_FILE="$OUTPUT_DIR/diamond_commands.txt"

# OrthoFinder refuses to run when the non-default -o output directory
# already exists. Create only the PARENT directory, and fail loudly if
# the target output directory itself is present.
mkdir -p "$(dirname "$OUTPUT_DIR")"

if [ -e "$OUTPUT_DIR" ]; then
    echo "ERROR: OrthoFinder output directory already exists: $OUTPUT_DIR"
    echo "Choose a fresh output_dir in pipeline_config.yaml."
    exit 1
fi

# Run OrthoFinder prepare phase. -op stops after writing the search
# commands and exits without running them.
orthofinder -f "$INPUT_DIR" -o "$OUTPUT_DIR" -op \\
    -S {config.orthofinder.sequence_search} \\
    > "$OUTPUT_DIR/prepare_full_stdout.log" 2>&1

PREPARE_EXIT=$?
if [ $PREPARE_EXIT -ne 0 ]; then
    echo "ERROR: OrthoFinder prepare phase failed with exit code $PREPARE_EXIT"
    cat "$OUTPUT_DIR/prepare_full_stdout.log"
    exit $PREPARE_EXIT
fi

# Extract search commands from OrthoFinder stdout. Diamond commands
# start with "diamond"; BLAST commands start with "blastp" or "makeblastdb".
grep -E "^(diamond|blastp|makeblastdb)" "$OUTPUT_DIR/prepare_full_stdout.log" > "$COMMANDS_FILE" || true

# OrthoFinder sometimes writes the commands list inside WorkingDirectory/.
# Use it as a fallback if the grep above produced nothing.
WORK_DIR=$(find "$OUTPUT_DIR" -maxdepth 2 -name "WorkingDirectory" -type d | head -1)
if [ -n "$WORK_DIR" ]; then
    for cmd_file in "$WORK_DIR"/Commands_*.txt; do
        if [ -f "$cmd_file" ] && [ ! -s "$COMMANDS_FILE" ]; then
            cp "$cmd_file" "$COMMANDS_FILE"
            echo "Found commands file: $cmd_file"
        fi
    done
fi

NUM_COMMANDS=$(wc -l < "$COMMANDS_FILE")
echo "Extracted $NUM_COMMANDS search commands to $COMMANDS_FILE"

if [ "$NUM_COMMANDS" -eq 0 ]; then
    echo "ERROR: No search commands were extracted."
    echo "Check $OUTPUT_DIR/prepare_full_stdout.log for details."
    exit 1
fi

# Persist the WorkingDirectory path for the resume script.
echo "$WORK_DIR" > "$OUTPUT_DIR/working_dir_path.txt"

ELAPSED=$(( SECONDS - START_SECONDS ))
HOURS=$(( ELAPSED / 3600 ))
MINUTES=$(( (ELAPSED % 3600) / 60 ))
SECS=$(( ELAPSED % 60 ))

echo ""
echo "============================================================"
echo "convgeno: prepare phase finished"
echo "End:       $(date)"
echo "Duration:  ${{HOURS}}h ${{MINUTES}}m ${{SECS}}s"
echo "============================================================"
exit 0
"""
    return script


def generate_search_array_script(
    config: PipelineConfig,
    commands_per_task: int = 50,
    array_max: int | None = None,
) -> str:
    """Generate SLURM array job that executes DIAMOND/BLAST search commands.

    Each array task runs ``commands_per_task`` commands from the file
    produced by the prepare phase. The array upper bound (``array_max``)
    must be computed by the caller from the actual input size — hard-
    coding a large value (e.g. ``0-9999``) is rejected by many SLURM
    clusters with ``Invalid job array specification``.

    Parameters
    ----------
    config:
        The pipeline configuration. Must include an ``orthofinder``
        section.
    commands_per_task:
        How many DIAMOND/BLAST commands each array task executes.
        Must be > 0.
    array_max:
        Inclusive upper bound for the SLURM array (the script will have
        ``#SBATCH --array=0-<array_max>``). Required; must be a
        non-negative integer. The CLI computes this from the number of
        input FASTA files so the array size is deterministic and tied
        to validation.

    Raises
    ------
    ValueError
        If ``config.orthofinder`` is missing, ``commands_per_task`` is
        not positive, or ``array_max`` is ``None`` or negative.
    """
    _validate_has_orthofinder(config)
    assert config.orthofinder is not None

    if commands_per_task <= 0:
        raise ValueError("commands_per_task must be positive")
    if array_max is None or array_max < 0:
        raise ValueError("array_max must be a non-negative integer")

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    header = _build_sbatch_header(
        config,
        overrides={
            "--job-name": "convgeno_of_search",
            "--nodes": "1",
            "--ntasks": "1",
            "--cpus-per-task": str(config.orthofinder.search_threads),
            "--time": config.slurm.time_limit,
            "--output": config.slurm.output_pattern.replace("%j", "%A_%a"),
            "--error": config.slurm.error_pattern.replace("%j", "%A_%a"),
            "--array": f"0-{array_max}",
        },
    )

    script = f"""\
#!/bin/bash
# ============================================================
# OrthoFinder search phase — SLURM array job (multi-node mode)
# Generated by convgeno on {timestamp}
# ============================================================

{header}

set -euo pipefail

echo "============================================================"
echo "convgeno: OrthoFinder search array task $SLURM_ARRAY_TASK_ID"
echo "Job ID:    $SLURM_JOB_ID (array job $SLURM_ARRAY_JOB_ID)"
echo "Node:      $HOSTNAME"
echo "Start:     $(date)"
echo "============================================================"

START_SECONDS=$SECONDS

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate {config.conda_env}

OUTPUT_DIR="{config.orthofinder.output_dir}"
COMMANDS_FILE="$OUTPUT_DIR/diamond_commands.txt"
COMMANDS_PER_TASK={commands_per_task}

if [ ! -f "$COMMANDS_FILE" ]; then
    echo "ERROR: Commands file not found: $COMMANDS_FILE"
    echo "The prepare job may have failed. Check its logs."
    exit 1
fi

TOTAL_COMMANDS=$(wc -l < "$COMMANDS_FILE")

START_LINE=$(( SLURM_ARRAY_TASK_ID * COMMANDS_PER_TASK + 1 ))
END_LINE=$(( START_LINE + COMMANDS_PER_TASK - 1 ))

# If this task's start line is beyond the total, this array slot has
# no work. Exit cleanly so the dependency chain can continue.
if [ "$START_LINE" -gt "$TOTAL_COMMANDS" ]; then
    echo "Task $SLURM_ARRAY_TASK_ID: no commands to run (start=$START_LINE > total=$TOTAL_COMMANDS). Exiting."
    exit 0
fi

if [ "$END_LINE" -gt "$TOTAL_COMMANDS" ]; then
    END_LINE=$TOTAL_COMMANDS
fi

echo "Total commands: $TOTAL_COMMANDS"
echo "This task runs commands $START_LINE to $END_LINE ($COMMANDS_PER_TASK per task)"
echo ""

FAILED=0
for LINE_NUM in $(seq $START_LINE $END_LINE); do
    CMD=$(sed -n "${{LINE_NUM}}p" "$COMMANDS_FILE")
    if [ -z "$CMD" ]; then
        continue
    fi
    echo "[Task $SLURM_ARRAY_TASK_ID] Running command $LINE_NUM: $CMD"
    eval "$CMD"
    CMD_EXIT=$?
    if [ $CMD_EXIT -ne 0 ]; then
        echo "WARNING: Command $LINE_NUM failed with exit code $CMD_EXIT"
        FAILED=$((FAILED + 1))
    fi
done

ELAPSED=$(( SECONDS - START_SECONDS ))
HOURS=$(( ELAPSED / 3600 ))
MINUTES=$(( (ELAPSED % 3600) / 60 ))
SECS=$(( ELAPSED % 60 ))

echo ""
echo "============================================================"
echo "convgeno: search array task $SLURM_ARRAY_TASK_ID finished"
echo "Commands run: $((END_LINE - START_LINE + 1))"
echo "Failed: $FAILED"
echo "Duration: ${{HOURS}}h ${{MINUTES}}m ${{SECS}}s"
echo "============================================================"

if [ $FAILED -gt 0 ]; then
    echo "WARNING: $FAILED command(s) failed. Check logs above."
    exit 1
fi

exit 0
"""
    return script


def generate_resume_script(config: PipelineConfig) -> str:
    """Generate SLURM script for OrthoFinder's resume phase (``-b``).

    Runs on a single node after all search array tasks complete. Resumes
    OrthoFinder from pre-computed search results, performing clustering,
    MSA, and tree inference.
    """
    _validate_has_orthofinder(config)
    assert config.orthofinder is not None

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    header = _build_sbatch_header(
        config,
        overrides={
            "--job-name": "convgeno_of_resume",
            "--nodes": "1",
            "--ntasks": "1",
            "--cpus-per-task": str(config.slurm.cpus_per_task),
            "--time": config.slurm.time_limit,
        },
    )

    # The resume command only needs -b, -t, and -a. The search/MSA/tree
    # programs were configured during the prepare phase and OrthoFinder
    # reads them from WorkingDirectory metadata.
    extra = " ".join(config.orthofinder.extra_args)
    extra_suffix = f" {extra}" if extra else ""

    script = f"""\
#!/bin/bash
# ============================================================
# OrthoFinder resume phase (-b) — multi-node mode
# Generated by convgeno on {timestamp}
# ============================================================

{header}

set -euo pipefail

echo "============================================================"
echo "convgeno: OrthoFinder resume phase started"
echo "Job ID:    $SLURM_JOB_ID"
echo "Node:      $HOSTNAME"
echo "Start:     $(date)"
echo "============================================================"

START_SECONDS=$SECONDS

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate {config.conda_env}

OUTPUT_DIR="{config.orthofinder.output_dir}"

# Find the WorkingDirectory created by the prepare phase.
WORK_DIR_FILE="$OUTPUT_DIR/working_dir_path.txt"
if [ -f "$WORK_DIR_FILE" ]; then
    WORK_DIR=$(cat "$WORK_DIR_FILE")
else
    WORK_DIR=$(find "$OUTPUT_DIR" -maxdepth 2 -name "WorkingDirectory" -type d | head -1)
fi

if [ -z "$WORK_DIR" ] || [ ! -d "$WORK_DIR" ]; then
    echo "ERROR: Could not find OrthoFinder WorkingDirectory in $OUTPUT_DIR"
    echo "The prepare job may have failed."
    exit 1
fi

echo "Resuming OrthoFinder from: $WORK_DIR"
echo ""

orthofinder -b "$WORK_DIR" -t {config.orthofinder.search_threads} -a {config.orthofinder.analysis_threads}{extra_suffix}

EXIT_CODE=$?

ELAPSED=$(( SECONDS - START_SECONDS ))
HOURS=$(( ELAPSED / 3600 ))
MINUTES=$(( (ELAPSED % 3600) / 60 ))
SECS=$(( ELAPSED % 60 ))

echo ""
echo "============================================================"
echo "convgeno: resume phase finished"
echo "Exit code: $EXIT_CODE"
echo "End:       $(date)"
echo "Duration:  ${{HOURS}}h ${{MINUTES}}m ${{SECS}}s"
echo "============================================================"

if [ $EXIT_CODE -ne 0 ]; then
    echo "ERROR: OrthoFinder resume phase exited with code $EXIT_CODE"
    exit $EXIT_CODE
fi

if [ ! -f "$OUTPUT_DIR"/*/Orthogroups/Orthogroups.tsv ] 2>/dev/null; then
    echo "WARNING: Expected output file Orthogroups.tsv not found in $OUTPUT_DIR"
    echo "Check $OUTPUT_DIR for a Results_* directory."
fi

echo "OrthoFinder multi-node run completed successfully."
exit 0
"""
    return script
