"""SLURM batch script generation for external bioinformatics tools."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from convgeno.slurm.config import PipelineConfig
from convgeno.slurm.runtime import CondaRuntimeConfig, render_conda_bootstrap


def generate_orthofinder_script(
    config: PipelineConfig,
    runtime: CondaRuntimeConfig | None = None,
) -> str:
    """Generate a SLURM batch script to run OrthoFinder.

    Parameters
    ----------
    config
        Pipeline configuration containing SLURM resources and
        OrthoFinder settings.
    runtime
        Conda runtime configuration for compute-node bootstrap.
        If ``None``, falls back to ``config.runtime``. At least one
        must be provided.

    Returns
    -------
    str
        Complete script ready to be written to disk and submitted
        with ``sbatch``.

    Raises
    ------
    ValueError
        If ``config.orthofinder`` is ``None`` or no runtime config
        is available.
    """
    if config.orthofinder is None:
        raise ValueError(
            "OrthoFinder settings not found in pipeline config. "
            "Add an 'orthofinder' section to pipeline_config.yaml."
        )

    resolved_runtime = runtime if runtime is not None else config.runtime
    if resolved_runtime is None:
        raise ValueError(
            "No runtime configuration provided. "
            "Run 'convgeno init' to detect and store conda paths."
        )

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    sbatch_lines = config.slurm.to_sbatch_lines()
    sbatch_lines.insert(0, "#SBATCH --job-name=convgeno_orthofinder")
    sbatch_lines.append("#SBATCH --export=ALL")

    of_args = config.orthofinder.to_command_args()
    of_command = "orthofinder " + " ".join(of_args)

    sbatch_block = "\n".join(sbatch_lines)
    bootstrap_block = render_conda_bootstrap(resolved_runtime)

    script = f"""\
#!/bin/bash
# ============================================================
# OrthoFinder SLURM batch script
# Generated by convgeno on {timestamp}
# ============================================================
#
# To submit:  sbatch this_script.sh
# To inspect: cat this_script.sh
#

{sbatch_block}

# ------------------------------------------------------------
# Environment setup
# ------------------------------------------------------------
set -euo pipefail

{bootstrap_block}

# Record start time for duration calculation
START_SECONDS=$SECONDS

# Verify OrthoFinder is available
if ! command -v orthofinder &> /dev/null; then
    echo "ERROR: orthofinder not found in conda environment"
    echo "Install with: conda install -c bioconda orthofinder"
    exit 1
fi

echo "OrthoFinder version:"
orthofinder -h 2>&1 | head -n 2 || true
echo ""

# ------------------------------------------------------------
# Validate inputs
# ------------------------------------------------------------
INPUT_DIR="{config.orthofinder.input_dir}"
OUTPUT_DIR="{config.orthofinder.output_dir}"

if [ ! -d "$INPUT_DIR" ]; then
    echo "ERROR: Input directory does not exist: $INPUT_DIR"
    exit 1
fi

FASTA_COUNT=$(find "$INPUT_DIR" -maxdepth 1 -name "*.fa" -o -name "*.fasta" -o -name "*.faa" | wc -l)
if [ "$FASTA_COUNT" -eq 0 ]; then
    echo "ERROR: No FASTA files (.fa, .fasta, .faa) found in $INPUT_DIR"
    exit 1
fi

echo "Input directory: $INPUT_DIR"
echo "FASTA files found: $FASTA_COUNT"
echo "Output directory: $OUTPUT_DIR"
echo ""

# OrthoFinder refuses to run when the non-default -o output directory
# already exists. Create only the PARENT directory, and fail loudly if
# the target output directory itself is present.
mkdir -p "$(dirname "$OUTPUT_DIR")"

if [ -e "$OUTPUT_DIR" ]; then
    echo "ERROR: OrthoFinder output directory already exists: $OUTPUT_DIR"
    echo "Choose a fresh output_dir in pipeline_config.yaml."
    exit 1
fi

# ------------------------------------------------------------
# Run OrthoFinder
# ------------------------------------------------------------
echo "Running OrthoFinder..."
echo "Command: {of_command}"
echo ""

{of_command}

EXIT_CODE=$?

# ------------------------------------------------------------
# Post-run validation
# ------------------------------------------------------------
ELAPSED=$(( SECONDS - START_SECONDS ))
HOURS=$(( ELAPSED / 3600 ))
MINUTES=$(( (ELAPSED % 3600) / 60 ))
SECS=$(( ELAPSED % 60 ))

echo ""
echo "============================================================"
echo "convgeno: OrthoFinder job finished"
echo "Exit code: $EXIT_CODE"
echo "End:       $(date)"
echo "Duration:  ${{HOURS}}h ${{MINUTES}}m ${{SECS}}s"
echo "============================================================"

if [ $EXIT_CODE -ne 0 ]; then
    echo "ERROR: OrthoFinder exited with code $EXIT_CODE"
    exit $EXIT_CODE
fi

# Check that key output files exist
if [ ! -f "$OUTPUT_DIR"/*/Orthogroups/Orthogroups.tsv ] 2>/dev/null; then
    echo "WARNING: Expected output file Orthogroups.tsv not found in $OUTPUT_DIR"
    echo "OrthoFinder may have written results to a subdirectory."
    echo "Check $OUTPUT_DIR for a Results_* directory."
fi

echo "OrthoFinder completed successfully."
exit 0
"""
    return script


def write_script(content: str, path: Path | str) -> Path:
    """Write a generated SLURM script to disk and make it executable.

    Returns the resolved path.
    """
    path = Path(path).resolve()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    path.chmod(path.stat().st_mode | 0o755)
    return path
